name: build

on:
  push:
    branches:
      - 'master'
  pull_request: {}

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
      - name: tests
        run: |
          make test
